# Generated by Django 4.2.16 on 2024-09-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions_rounds", "0001_initial"),
        ("achievements", "0005_alter_achievements_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "participants",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="ParticipantAchievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievements",
                    ),
                ),
                (
                    "participants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.participants",
                    ),
                ),
                (
                    "rounds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions_rounds.rounds",
                    ),
                ),
                (
                    "sessions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions_rounds.sessions",
                    ),
                ),
            ],
            options={
                "db_table": "participant_achievements",
            },
        ),
    ]
