# Generated by Django 4.2.16 on 2024-09-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantachievements",
            old_name="achievements",
            new_name="achievement",
        ),
        migrations.RenameField(
            model_name="participantachievements",
            old_name="participants",
            new_name="participant",
        ),
        migrations.RenameField(
            model_name="participantachievements",
            old_name="rounds",
            new_name="round",
        ),
        migrations.RenameField(
            model_name="participantachievements",
            old_name="sessions",
            new_name="session",
        ),
    ]
