# Generated by Django 4.2.16 on 2024-09-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_participant_created_at_participant_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Participants',
        ),
    ]
