# Generated by Django 4.2.16 on 2024-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_rename_achievements_participantachievements_achievement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participantachievements",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
