# Generated by Django 4.2.16 on 2024-09-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_participantachievements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantachievements",
            old_name="achievement_id",
            new_name="achievements",
        ),
        migrations.RenameField(
            model_name="participantachievements",
            old_name="participant_id",
            new_name="participants",
        ),
        migrations.RenameField(
            model_name="participantachievements",
            old_name="round_id",
            new_name="rounds",
        ),
        migrations.RenameField(
            model_name="participantachievements",
            old_name="session_id",
            new_name="sessions",
        ),
    ]
