# Generated by Django 4.2.16 on 2024-09-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_participant_participants'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participants',
            table='participants',
        ),
    ]
