# Generated by Django 4.2.16 on 2024-09-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('point_value', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('nested', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'restrictions',
            },
        ),
        migrations.CreateModel(
            name='AchievementsRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievements')),
                ('restrictions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.restrictions')),
            ],
            options={
                'db_table': 'achievements_restrictions',
            },
        ),
        migrations.AddField(
            model_name='achievements',
            name='restrictions',
            field=models.ManyToManyField(through='achievements.AchievementsRestrictions', to='achievements.restrictions'),
        ),
    ]
