# Generated by Django 4.2.16 on 2024-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="parent_id",
            field=models.IntegerField(null=True),
        ),
    ]
