# Generated by Django 4.2.16 on 2024-09-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_alter_achievements_parent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievements",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="achievements",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="achievements.achievements",
            ),
        ),
    ]
