# Generated by Django 4.2.16 on 2024-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0003_remove_achievements_parent_id_achievements_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="point_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
