# Generated by Django 4.2.16 on 2024-09-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0004_alter_achievements_point_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="achievements.achievements",
            ),
        ),
    ]
