# Generated by Django 4.2.16 on 2024-10-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_rename_achievements_participantachievements_achievement_and_more",
        ),
        ("sessions_rounds", "0003_pods_submitted"),
        ("achievements", "0005_alter_achievements_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=5)),
                ("slug", models.CharField(max_length=26)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "colors",
            },
        ),
        migrations.CreateModel(
            name="WinningCommanders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "colors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.colors",
                    ),
                ),
                (
                    "participants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.participants",
                    ),
                ),
                (
                    "pods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions_rounds.pods",
                    ),
                ),
            ],
            options={
                "db_table": "winning_commanders",
            },
        ),
        migrations.CreateModel(
            name="ColorFactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "colors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.colors",
                    ),
                ),
            ],
            options={
                "db_table": "color_factions",
            },
        ),
    ]
