# Generated by Django 4.2.16 on 2024-10-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0006_colors_winningcommanders_colorfactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievements",
            name="description",
        ),
    ]
