# Generated by Django 4.2.16 on 2024-09-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("sessions_rounds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podsparticipants",
            name="participants",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.participants"
            ),
        ),
        migrations.AddField(
            model_name="podsparticipants",
            name="pods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessions_rounds.pods"
            ),
        ),
        migrations.AddField(
            model_name="pods",
            name="rounds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessions_rounds.rounds"
            ),
        ),
    ]
